from typing import Set, Dict, Optional, Any, Union
from configparser import RawConfigParser

class Tags:
    def __init__(self, config: 'GhostConfig', node: str) -> None: ...
    def __iter__(self) -> str: ...
    def get(self) -> Set[str]: ...
    def set(self, tags: Set[str]) -> None: ...
    def add(self, *tags: str) -> None: ...
    def remove(self, *tags: str) -> None: ...
    def clear(self) -> None: ...
    def __str__(self) -> str: ...

class GhostConfig(RawConfigParser):
    def __init__(self, config: str = 'ghost.conf') -> None: ...
    def tags(self, node: Union[int, str]) -> Tags: ...
    def by_tags(self, tags: str) -> list: ...
    def save(self, project: bool = True, user: bool = False) -> None: ...
    def get_path(self, filepath: str, substitutions: Dict[str, Any] = {}, create: bool = True, dir: bool = False) -> str: ...