from typing import List, Optional, Any
from threading import Event, Lock
from .GhostModule import GhostModule
from .GhostErrors import GhostModuleError, GhostModuleExit

class Thread:
    def _get_my_tid(self) -> int: ...
    def raise_exc(self, exctype: type) -> None: ...
    def stop(self) -> None: ...

class ThreadPool:
    def __init__(self) -> None: ...
    def apply_async(self, func: callable, args: tuple) -> None: ...
    def interrupt_all(self) -> None: ...
    def interrupt(self) -> None: ...
    def join(self, timeout: int = 5, on_interrupt: Optional[callable] = None) -> bool: ...
    def all_finished(self) -> bool: ...

class GhostJob:
    def __init__(self, pupsrv: Any, module: type, name: str, args: Any) -> None: ...
    @property
    def module(self) -> type: ...
    @property
    def clients(self) -> list: ...
    def add_module(self, mod: GhostModule) -> None: ...
    def stop(self) -> None: ...
    def module_worker(self, module: GhostModule, once: bool) -> None: ...
    def start(self, once: bool = False) -> None: ...
    def interrupt(self) -> bool: ...
    def interactive_wait(self) -> bool: ...
    def check(self) -> None: ...
    def is_finished(self) -> bool: ...